name: Build and test

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Bootstrap work environment
      shell: bash
      working-directory: ${{github.workspace}}
      run: python bootstrap.py

    - name: Build
      working-directory: ${{github.workspace}}/bin
      shell: bash
      run: cmake --build .

    - name: Test
      working-directory: ${{github.workspace}}/bin
      shell: bash
      run: ctest --output-on-failure -C Release
