name: Build and test

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure
      working-directory: ${{github.workspace}}
      shell: bash
      run: mkdir bin && cd bin && cmake ..  

    - name: Build
      working-directory: ${{github.workspace}}/bin
      shell: bash
      run: cmake --build .

    - name: Test
      working-directory: ${{github.workspace}}/bin
      shell: bash
      run: ctest --output-on-failure -C Debug -E parser
